[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
deauth-fractional-marketplace = "DLjJEsDLtUiJtMuHjurKhyba1YehvGNWXXWdM7jK3cBi"
deauth_fractional_nft = "82547nhsM6oQdyDdNNiHvZEnZHRbzVfq9CKb2jUYaqaS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
